language: node_js
node_js:
  - 'stable'

services:
  - postgresql

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@/travis_ci_test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# after_success: npm run coverage
