language: node_js
node_js:
  - 'stable'

services:
  - postgresql

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@/travis_ci_test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - npm run coverage

before_deploy:
  - serverless config credentials --provider aws --profile cs3219-otot-task-b --key "$AWS_ACCESS_KEY_ID" --secret "$AWS_SECRET_ACCESS_KEY"

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: main
