service: cs3219-otot-task-b
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  memorySize: 512
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true
